// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtin5O3Y3XJ01VMT6F7jqK7AD3d55Kmpc',
    appId: '1:674393003989:web:820de80f78ddce0f874f5c',
    messagingSenderId: '674393003989',
    projectId: 'todo-d23a1',
    authDomain: 'todo-d23a1.firebaseapp.com',
    storageBucket: 'todo-d23a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeWv9SDDrT-aW9Ku8-yTM-MqvSsYKcOxA',
    appId: '1:674393003989:android:93204964bd71c9a9874f5c',
    messagingSenderId: '674393003989',
    projectId: 'todo-d23a1',
    storageBucket: 'todo-d23a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZvdj1bSFityEveWFKvXINxe7EFsQLKcI',
    appId: '1:674393003989:ios:b543708ffd148b65874f5c',
    messagingSenderId: '674393003989',
    projectId: 'todo-d23a1',
    storageBucket: 'todo-d23a1.firebasestorage.app',
    iosBundleId: 'dev.paul-matencio.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZvdj1bSFityEveWFKvXINxe7EFsQLKcI',
    appId: '1:674393003989:ios:200022fd3209a340874f5c',
    messagingSenderId: '674393003989',
    projectId: 'todo-d23a1',
    storageBucket: 'todo-d23a1.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtin5O3Y3XJ01VMT6F7jqK7AD3d55Kmpc',
    appId: '1:674393003989:web:fe6b179f84b529ff874f5c',
    messagingSenderId: '674393003989',
    projectId: 'todo-d23a1',
    authDomain: 'todo-d23a1.firebaseapp.com',
    storageBucket: 'todo-d23a1.firebasestorage.app',
  );

}